require:
  - rubocop-erb
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/**/*.erb
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-erb.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false
